export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: [
    '@nuxtjs/supabase',
    '@nuxt/icon',
    'nuxt-auth-utils',
    '@nuxtjs/i18n',
  ],

  i18n: {
    strategy: 'no_prefix',
    defaultLocale: 'en',
    locales: [
      { code: 'en', language: 'en-US', name: 'English', file: 'en.json' },
      { code: 'id', language: 'id-ID', name: 'Bahasa Indonesia', file: 'id.json' },
    ],
    langDir: 'locales/',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'purela_lang',
      cookieSecure: true,
      redirectOn: 'root',
      fallbackLocale: 'en',
      alwaysRedirect: false,
    },
    bundle: {
      optimizeTranslationDirective: false,
    },
  },

  // Tailwind is compiled by the standalone tailwindcss CLI (npm scripts
  // `build:css` and the watcher inside `dev`) into `public/tailwind.css`,
  // and referenced as a static stylesheet via `app.head.link` below.
  // Why not `css: ['~/assets/.../tailwind.css']` or an SFC import? Both
  // make Nuxt 3.17 + Vite 6 emit `<link rel="stylesheet">` to a Vite dev
  // URL that responds with Content-Type: text/css but a JavaScript body
  // (the HMR module wrapper) — the browser silently fails to parse it
  // and ships an unstyled page. Bypassing Vite for the global stylesheet
  // sidesteps the bug entirely; the file in `public/` is served verbatim.

  // The @nuxtjs/supabase module reads SUPABASE_URL, SUPABASE_KEY (anon),
  // and SUPABASE_SERVICE_KEY directly from env. Server routes use
  // serverSupabaseServiceRole(event) from #supabase/server for privileged
  // operations; the anon client is available client-side via useSupabaseClient.
  supabase: {
    redirect: false,
  },

  runtimeConfig: {
    dashboardPassword: '',  // NUXT_DASHBOARD_PASSWORD
    // nuxt-auth-utils reads NUXT_SESSION_PASSWORD automatically.
    public: {
      appName: 'Purela Dashboard',
    },
  },

  app: {
    head: {
      title: 'Purela Dashboard',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Purela brand performance dashboard' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        // Compiled Tailwind output. Generated by `npm run build:css` (or the
        // watcher in `npm run dev`). Served verbatim from public/.
        { rel: 'stylesheet', href: '/tailwind.css' },
        // Source Serif 4 for display headings, Inter for body — matches the
        // "calm, paper-like" aesthetic.
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:opsz,wght@8..60,400;8..60,500;8..60,600&display=swap',
        },
      ],
    },
  },

  nitro: {
    preset: 'netlify',
    // papaparse's UMD wrapper trips rollup's CJS parser; xlsx is huge.
    // Keep both out of the rollup bundle and let Nitro require them at runtime.
    rollupConfig: {
      external: ['papaparse', 'xlsx'],
    },
  },

  typescript: {
    strict: true,
  },

  compatibilityDate: '2025-05-06',
})
